# ===========================================
# CLOUD BUILD CONFIG FOR GOOGLE CLOUD RUN
# ===========================================
# Deploy with: gcloud builds submit --config cloudbuild.yaml
# Or set up a trigger in Cloud Build for automatic deployments

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/blog-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/blog-backend:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/blog-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/blog-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'blog-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/blog-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod'
      - '--set-env-vars'
      - '^@^ALLOWED_ORIGINS=https://harrysblog.vercel.app,http://localhost:5173'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/blog-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/blog-backend:latest'

# Substitution variables (override with --substitutions)
substitutions:
  _REGION: 'asia-south1'

# Build timeout
timeout: '1200s'
